name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Transfer Caddyfile to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "Caddyfile"
          target: "/opt/sewer-comedy"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Reload Caddy
            cd /opt/sewer-comedy
            caddy adapt --config Caddyfile --pretty > caddy.json
            caddy reload --config caddy.json

            # Ensure Docker is logged in
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull the latest image
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop and remove existing container
            docker stop sewer-app || true
            docker rm sewer-app || true

            # Run new container
            docker run -d \
              --name sewer-app \
              --restart unless-stopped \
              --network host \
              -e DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}" \
              -e REDIS_URL="${{ secrets.PROD_REDIS_URL }}" \
              -e REDIS_PASSWD="${{ secrets.PROD_REDIS_PASSWD }}" \
              -e BETTER_AUTH_SECRET="${{ secrets.PROD_BETTER_AUTH_SECRET }}" \
              -e BETTER_AUTH_BASE_URL="${{ secrets.PROD_BETTER_AUTH_BASE_URL }}" \
              -e S3_ENDPOINT="${{ vars.S3_ENDPOINT }}" \
              -e S3_REGION="${{ vars.S3_REGION }}" \
              -e S3_ACCESS_KEY="${{ secrets.PROD_S3_ACCESS_KEY }}" \
              -e S3_SECRET_KEY="${{ secrets.PROD_S3_SECRET_KEY }}" \
              -e S3_BUCKET_NAME="${{ vars.S3_BUCKET_NAME }}" \
              -e S3_CDN_URL="${{ vars.S3_CDN_URL }}" \
              -e RESEND_API_KEY="${{ secrets.PROD_RESEND_API_KEY }}" \
              -e ORIGIN="https://sewercomedy.fun" \
              -e NODE_ENV="production" \
              -e BODY_SIZE_LIMIT="10M" \
              ghcr.io/${{ github.repository }}:latest

            # Prune old images
            docker image prune -f
